import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ButtonTheme } from "@/components/button/ButtonTheme";
import { NavbarRoute } from "@/components/layout/NavbarRoute";
import { SessionProvider } from "next-auth/react";  // นำเข้า SessionProvider
import ClientLayout from "@/components/ClientLayout";  // นำเข้า ClientLayout

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
        <body className={geistSans.variable + " " + geistMono.variable}>
        {/* ห่อหุ้ม children ด้วย SessionProvider */}
        <ClientLayout>
            <ButtonTheme />
            <NavbarRoute />
            {children}
        </ClientLayout>
        </body>
        </html>
    );
}
